= Multi-Region Deployment

This configuration consists of a cluster of nodes that are deployed within three AWS data centers: One in the ```us-east-1``` region, connected to two other clusters of nodes, deployed respectively within the ```eu-west-3``` and ```ap-northeast-1``` regions. Each node is deployed in a distinct availability zone.

The availability zone ID is assigned to each node. This ID is used to map the node to a physical rack or logical zone. This configuration ensures that leaseholder ranges, the corresponding replicas, and associated endpoints are placed on nodes in different racks/zones.

image::images/Multi-Region-Multi-AZ.svg[Multi-Region Multi-Zonal Configuration]

As per above architecture, we create :

- 3 VPC in three Regions - US-East-1, EU-West-2, and AP-NorthEast-1,
- 3 EC2 Instances per region,
- 1 VPC per region with 3 Subnets, each subnet in a different availability zone,
- 1 Network Load Balancer per region to distribute traffic within regions,
- 1 name server with a weighted traffic policy to distribute traffic across multiple regions.

[IMPORTANT]
.Load Balancing
====
Both https://aws.amazon.com/route53/[Route53] and https://docs.aws.amazon.com/elasticloadbalancing/latest/userguide/what-is-load-balancing.html[ELB] are used to distribute the network traffic.

ELB distributes traffic among Multiple Availability Zone but not to multiple Regions. Route53 can distribute traffic among multiple Regions.
====